import registerUserAPI from "../services/registerUserAPI";
import loginUserAPI from "../services/loginUserAPI";

const getState = ({ getStore, getActions, setStore }) => {
    const backendUrl = 'http://192.168.1.11:5000'
    const apiKey = '97c4dd2b-fe2e-4407-8ea3-f26435d6ce9b'
    return {
        store: {
            
            pl_players: [],
            playersPage: 1,
            playersCount: [],   
            playersCountTotal: [],
            totalPlayerPages: [],
            leagues: [],
            leaguesPage: 1,
            leaguesCount: [],   
            leaguesCountTotal: [],
            totalLeaguesPages: [],
            clubs: [],
            clubsPage: 1,
            clubsCount: [],   
            clubsCountTotal: [],
            totalClubsPages: [],
            nations: [],
            nationsPage: 1,
            nationsCount: [],   
            nationsCountTotal: [],
            totalNationsPages: [],
            rarities: [],
            raritiesPage: 1,
            raritiesCount: [],   
            raritiesCountTotal: [],
            totalRaritiesPages: [],
            user: {},
            token: '',
            registerFormData: {
                username: '',
                email: '',
                password: ''
            },
            loginFormData: {
                username: '',
                password: ''
            },
            error: false,
            plSquad: {}


        },
        actions: {
            registerUser: async (user) => {
                const us = await registerUserAPI(user).then((data) => {
                    console.log(data)
                    setStore({...getStore, user: us})  
                })
            },
            loginUser: async (user) => {
                const us = await loginUserAPI(user).then((data) => {
                    console.log(data)
                    setStore({...getStore, token: data.token})
                    //localStorage.setItem("jwt-token", data.token);
                 })
            },
            getSquad: () => {
                return ({
                    CAM: {
                    acceleration: 80,
                    aggression: 73,
                    agility: 92,
                    attack_work_rate: "Med",
                    balance: 83,
                    ball_control: 89,
                    cam_meta_rating: 93.19,
                    cb_meta_rating: 74.21000000000001,
                    cdm_meta_rating: 69.66,
                    club: 240,
                    cm_meta_rating: 78.88000000000001,
                    common_name: "Griezmann",
                    composure: 90,
                    crossing: 83,
                    curve: 86,
                    defending: 52,
                    defense_work_rate: "Med",
                    dribbling: 85,
                    dribbling_face: 87,
                    fb_meta_rating: 77.98000000000002,
                    finishing: 84,
                    first_name: "Antoine",
                    foot: "Left",
                    free_kick_accuracy: 85,
                    heading_accuracy: 83,
                    height: 176,
                    id: 845,
                    interceptions: 49,
                    jumping: 90,
                    last_name: "Antoine Griezmann",
                    league: 53,
                    long_passing: 82,
                    long_shots: 83,
                    name: "Antoine Griezmann",
                    nation: 18,
                    pace: 80,
                    passing: 84,
                    penalties: 79,
                    physicality: 72,
                    position: "ST",
                    positioning: 89,
                    rarity: 1,
                    rating: 85,
                    reactions: 89,
                    resource_id: 194765,
                    shooting: 84,
                    short_passing: 84,
                    shot_power: 82,
                    skill_moves: 4,
                    sliding_tackle: 49,
                    sprint_speed: 80,
                    st_meta_rating: 92.1556,
                    stamina: 86,
                    standing_tackle: 54,
                    strength: 63,
                    vision: 85,
                    volleys: 86,
                    weak_foot: 3,
                    weight: 73,
                    wing_meta_rating: 88.67900000000002
                    },
                    CB1: {
                    acceleration: 91,
                    aggression: 82,
                    agility: 81,
                    attack_work_rate: "High",
                    balance: 78,
                    ball_control: 78,
                    cam_meta_rating: 87.96000000000002,
                    cb_meta_rating: 87.82,
                    cdm_meta_rating: 79.87,
                    club: 243,
                    cm_meta_rating: 79.5,
                    common_name: "Mendy",
                    composure: 78,
                    crossing: 78,
                    curve: 72,
                    defending: 78,
                    defense_work_rate: "High",
                    dribbling: 80,
                    dribbling_face: 79,
                    fb_meta_rating: 84.45000000000002,
                    finishing: 63,
                    first_name: "Ferland",
                    foot: "Left",
                    free_kick_accuracy: 35,
                    heading_accuracy: 72,
                    height: 180,
                    id: 886,
                    interceptions: 79,
                    jumping: 79,
                    last_name: "Ferland Mendy",
                    league: 53,
                    long_passing: 78,
                    long_shots: 64,
                    name: "Ferland Mendy",
                    nation: 18,
                    pace: 92,
                    passing: 76,
                    penalties: 49,
                    physicality: 84,
                    position: "LB",
                    positioning: 80,
                    rarity: 1,
                    rating: 83,
                    reactions: 82,
                    resource_id: 228618,
                    shooting: 64,
                    short_passing: 80,
                    shot_power: 69,
                    skill_moves: 4,
                    sliding_tackle: 80,
                    sprint_speed: 92,
                    st_meta_rating: 86.95899999999999,
                    stamina: 89,
                    standing_tackle: 81,
                    strength: 83,
                    vision: 75,
                    volleys: 50,
                    weak_foot: 5,
                    weight: 73,
                    wing_meta_rating: 83.42199999999998
                    },
                    CB2: {
                    acceleration: 60,
                    aggression: 91,
                    agility: 61,
                    attack_work_rate: "High",
                    balance: 66,
                    ball_control: 79,
                    cam_meta_rating: 84.09,
                    cb_meta_rating: 87.37999999999998,
                    cdm_meta_rating: 78.72,
                    club: 243,
                    cm_meta_rating: 76.98,
                    common_name: "Casemiro",
                    composure: 84,
                    crossing: 58,
                    curve: 62,
                    defending: 86,
                    defense_work_rate: "High",
                    dribbling: 69,
                    dribbling_face: 73,
                    fb_meta_rating: 76.65,
                    finishing: 64,
                    first_name: "Carlos Henrique",
                    foot: "Right",
                    free_kick_accuracy: 74,
                    heading_accuracy: 79,
                    height: 185,
                    id: 877,
                    interceptions: 87,
                    jumping: 87,
                    last_name: "Casemiro",
                    league: 53,
                    long_passing: 84,
                    long_shots: 81,
                    name: "Casemiro",
                    nation: 54,
                    pace: 65,
                    passing: 76,
                    penalties: 66,
                    physicality: 90,
                    position: "CDM",
                    positioning: 75,
                    rarity: 1,
                    rating: 89,
                    reactions: 87,
                    resource_id: 200145,
                    shooting: 73,
                    short_passing: 84,
                    shot_power: 88,
                    skill_moves: 2,
                    sliding_tackle: 87,
                    sprint_speed: 69,
                    st_meta_rating: 81.5216,
                    stamina: 89,
                    standing_tackle: 88,
                    strength: 90,
                    vision: 80,
                    volleys: 62,
                    weak_foot: 3,
                    weight: 84,
                    wing_meta_rating: 74.1446
                    },
                    CDM: {
                    acceleration: 91,
                    aggression: 82,
                    agility: 81,
                    attack_work_rate: "High",
                    balance: 78,
                    ball_control: 78,
                    cam_meta_rating: 87.96000000000002,
                    cb_meta_rating: 87.82,
                    cdm_meta_rating: 79.87,
                    club: 243,
                    cm_meta_rating: 79.5,
                    common_name: "Mendy",
                    composure: 78,
                    crossing: 78,
                    curve: 72,
                    defending: 78,
                    defense_work_rate: "High",
                    dribbling: 80,
                    dribbling_face: 79,
                    fb_meta_rating: 84.45000000000002,
                    finishing: 63,
                    first_name: "Ferland",
                    foot: "Left",
                    free_kick_accuracy: 35,
                    heading_accuracy: 72,
                    height: 180,
                    id: 886,
                    interceptions: 79,
                    jumping: 79,
                    last_name: "Ferland Mendy",
                    league: 53,
                    long_passing: 78,
                    long_shots: 64,
                    name: "Ferland Mendy",
                    nation: 18,
                    pace: 92,
                    passing: 76,
                    penalties: 49,
                    physicality: 84,
                    position: "LB",
                    positioning: 80,
                    rarity: 1,
                    rating: 83,
                    reactions: 82,
                    resource_id: 228618,
                    shooting: 64,
                    short_passing: 80,
                    shot_power: 69,
                    skill_moves: 4,
                    sliding_tackle: 80,
                    sprint_speed: 92,
                    st_meta_rating: 86.95899999999999,
                    stamina: 89,
                    standing_tackle: 81,
                    strength: 83,
                    vision: 75,
                    volleys: 50,
                    weak_foot: 5,
                    weight: 73,
                    wing_meta_rating: 83.42199999999998
                    },
                    CM: {
                    acceleration: 80,
                    aggression: 75,
                    agility: 88,
                    attack_work_rate: "High",
                    balance: 79,
                    ball_control: 89,
                    cam_meta_rating: 91.89999999999998,
                    cb_meta_rating: 84.99,
                    cdm_meta_rating: 76.91,
                    club: 241,
                    cm_meta_rating: 80.22,
                    common_name: "de Jong",
                    composure: 90,
                    crossing: 78,
                    curve: 84,
                    defending: 77,
                    defense_work_rate: "Med",
                    dribbling: 88,
                    dribbling_face: 88,
                    fb_meta_rating: 84.61999999999999,
                    finishing: 72,
                    first_name: "Frenkie",
                    foot: "Right",
                    free_kick_accuracy: 64,
                    heading_accuracy: 72,
                    height: 180,
                    id: 863,
                    interceptions: 82,
                    jumping: 76,
                    last_name: "Frenkie de Jong",
                    league: 53,
                    long_passing: 87,
                    long_shots: 66,
                    name: "Frenkie de Jong",
                    nation: 34,
                    pace: 81,
                    passing: 85,
                    penalties: 45,
                    physicality: 78,
                    position: "CM",
                    positioning: 77,
                    rarity: 1,
                    rating: 87,
                    reactions: 88,
                    resource_id: 228702,
                    shooting: 69,
                    short_passing: 91,
                    shot_power: 68,
                    skill_moves: 4,
                    sliding_tackle: 77,
                    sprint_speed: 82,
                    st_meta_rating: 89.15790000000001,
                    stamina: 90,
                    standing_tackle: 76,
                    strength: 74,
                    vision: 86,
                    volleys: 70,
                    weak_foot: 3,
                    weight: 74,
                    wing_meta_rating: 84.8392
                    },
                    LB: {
                    acceleration: 91,
                    aggression: 82,
                    agility: 81,
                    attack_work_rate: "High",
                    balance: 78,
                    ball_control: 78,
                    cam_meta_rating: 87.96000000000002,
                    cb_meta_rating: 87.82,
                    cdm_meta_rating: 79.87,
                    club: 243,
                    cm_meta_rating: 79.5,
                    common_name: "Mendy",
                    composure: 78,
                    crossing: 78,
                    curve: 72,
                    defending: 78,
                    defense_work_rate: "High",
                    dribbling: 80,
                    dribbling_face: 79,
                    fb_meta_rating: 84.45000000000002,
                    finishing: 63,
                    first_name: "Ferland",
                    foot: "Left",
                    free_kick_accuracy: 35,
                    heading_accuracy: 72,
                    height: 180,
                    id: 886,
                    interceptions: 79,
                    jumping: 79,
                    last_name: "Ferland Mendy",
                    league: 53,
                    long_passing: 78,
                    long_shots: 64,
                    name: "Ferland Mendy",
                    nation: 18,
                    pace: 92,
                    passing: 76,
                    penalties: 49,
                    physicality: 84,
                    position: "LB",
                    positioning: 80,
                    rarity: 1,
                    rating: 83,
                    reactions: 82,
                    resource_id: 228618,
                    shooting: 64,
                    short_passing: 80,
                    shot_power: 69,
                    skill_moves: 4,
                    sliding_tackle: 80,
                    sprint_speed: 92,
                    st_meta_rating: 86.95899999999999,
                    stamina: 89,
                    standing_tackle: 81,
                    strength: 83,
                    vision: 75,
                    volleys: 50,
                    weak_foot: 5,
                    weight: 73,
                    wing_meta_rating: 83.42199999999998
                    },
                    LW: {
                    acceleration: 86,
                    aggression: 54,
                    agility: 87,
                    attack_work_rate: "Med",
                    balance: 89,
                    ball_control: 88,
                    cam_meta_rating: 92.18,
                    cb_meta_rating: 62.48000000000001,
                    cdm_meta_rating: 62.56,
                    club: 243,
                    cm_meta_rating: 76.23,
                    common_name: "Hazard",
                    composure: 89,
                    crossing: 77,
                    curve: 83,
                    defending: 35,
                    defense_work_rate: "Med",
                    dribbling: 89,
                    dribbling_face: 88,
                    fb_meta_rating: 74.83,
                    finishing: 78,
                    first_name: "Eden",
                    foot: "Right",
                    free_kick_accuracy: 79,
                    heading_accuracy: 61,
                    height: 175,
                    id: 883,
                    interceptions: 41,
                    jumping: 55,
                    last_name: "Eden Hazard",
                    league: 53,
                    long_passing: 81,
                    long_shots: 77,
                    name: "Eden Hazard",
                    nation: 7,
                    pace: 84,
                    passing: 82,
                    penalties: 87,
                    physicality: 63,
                    position: "LW",
                    positioning: 83,
                    rarity: 1,
                    rating: 85,
                    reactions: 79,
                    resource_id: 183277,
                    shooting: 80,
                    short_passing: 85,
                    shot_power: 82,
                    skill_moves: 4,
                    sliding_tackle: 22,
                    sprint_speed: 82,
                    st_meta_rating: 89.25150000000001,
                    stamina: 77,
                    standing_tackle: 27,
                    strength: 61,
                    vision: 84,
                    volleys: 82,
                    weak_foot: 4,
                    weight: 74,
                    wing_meta_rating: 86.49260000000001
                    },
                    RB: {
                    acceleration: 81,
                    aggression: 86,
                    agility: 81,
                    attack_work_rate: "High",
                    balance: 86,
                    ball_control: 77,
                    cam_meta_rating: 86.20000000000002,
                    cb_meta_rating: 84.48,
                    cdm_meta_rating: 76.53999999999999,
                    club: 448,
                    cm_meta_rating: 76.2,
                    common_name: "Capa",
                    composure: 78,
                    crossing: 81,
                    curve: 80,
                    defending: 74,
                    defense_work_rate: "High",
                    dribbling: 76,
                    dribbling_face: 77,
                    fb_meta_rating: 81.67999999999999,
                    finishing: 56,
                    first_name: "Ander",
                    foot: "Right",
                    free_kick_accuracy: 58,
                    heading_accuracy: 60,
                    height: 175,
                    id: 902,
                    interceptions: 76,
                    jumping: 81,
                    last_name: "Ander Capa Rodríguez",
                    league: 53,
                    long_passing: 67,
                    long_shots: 67,
                    name: "Ander Capa Rodríguez",
                    nation: 45,
                    pace: 82,
                    passing: 76,
                    penalties: 54,
                    physicality: 88,
                    position: "RB",
                    positioning: 76,
                    rarity: 1,
                    rating: 80,
                    reactions: 74,
                    resource_id: 216189,
                    shooting: 64,
                    short_passing: 80,
                    shot_power: 83,
                    skill_moves: 3,
                    sliding_tackle: 76,
                    sprint_speed: 83,
                    st_meta_rating: 84.28099999999998,
                    stamina: 93,
                    standing_tackle: 78,
                    strength: 86,
                    vision: 75,
                    volleys: 54,
                    weak_foot: 3,
                    weight: 75,
                    wing_meta_rating: 82.06839999999998
                    },
                    RW: {
                    acceleration: 94,
                    aggression: 54,
                    agility: 89,
                    attack_work_rate: "High",
                    balance: 80,
                    ball_control: 84,
                    cam_meta_rating: 88.97,
                    cb_meta_rating: 63.780000000000015,
                    cdm_meta_rating: 61.75,
                    club: 241,
                    cm_meta_rating: 73.25,
                    common_name: "Dembélé",
                    composure: 80,
                    crossing: 81,
                    curve: 82,
                    defending: 36,
                    defense_work_rate: "Med",
                    dribbling: 89,
                    dribbling_face: 86,
                    fb_meta_rating: 73.96999999999998,
                    finishing: 75,
                    first_name: "Ousmane",
                    foot: "Left",
                    free_kick_accuracy: 64,
                    heading_accuracy: 43,
                    height: 178,
                    id: 868,
                    interceptions: 36,
                    jumping: 58,
                    last_name: "Ousmane Dembélé",
                    league: 53,
                    long_passing: 76,
                    long_shots: 76,
                    name: "Ousmane Dembélé",
                    nation: 18,
                    pace: 93,
                    passing: 77,
                    penalties: 75,
                    physicality: 56,
                    position: "RW",
                    positioning: 77,
                    rarity: 1,
                    rating: 83,
                    reactions: 78,
                    resource_id: 231443,
                    shooting: 77,
                    short_passing: 78,
                    shot_power: 83,
                    skill_moves: 5,
                    sliding_tackle: 33,
                    sprint_speed: 93,
                    st_meta_rating: 88.6902,
                    stamina: 68,
                    standing_tackle: 30,
                    strength: 51,
                    vision: 76,
                    volleys: 76,
                    weak_foot: 5,
                    weight: 67,
                    wing_meta_rating: 86.37259999999999
                    },
                    ST: {
                    acceleration: 77,
                    aggression: 63,
                    agility: 79,
                    attack_work_rate: "Med",
                    balance: 72,
                    ball_control: 90,
                    cam_meta_rating: 90.97,
                    cb_meta_rating: 65.29,
                    cdm_meta_rating: 64.66,
                    club: 243,
                    cm_meta_rating: 78,
                    common_name: "Benzema",
                    composure: 90,
                    crossing: 75,
                    curve: 81,
                    defending: 39,
                    defense_work_rate: "Med",
                    dribbling: 87,
                    dribbling_face: 87,
                    fb_meta_rating: 71.31,
                    finishing: 90,
                    first_name: "Karim",
                    foot: "Right",
                    free_kick_accuracy: 73,
                    heading_accuracy: 89,
                    height: 185,
                    id: 879,
                    interceptions: 39,
                    jumping: 79,
                    last_name: "Karim Benzema",
                    league: 53,
                    long_passing: 73,
                    long_shots: 79,
                    name: "Karim Benzema",
                    nation: 18,
                    pace: 76,
                    passing: 81,
                    penalties: 84,
                    physicality: 77,
                    position: "CF",
                    positioning: 90,
                    rarity: 1,
                    rating: 89,
                    reactions: 91,
                    resource_id: 165153,
                    shooting: 86,
                    short_passing: 86,
                    shot_power: 85,
                    skill_moves: 4,
                    sliding_tackle: 18,
                    sprint_speed: 75,
                    st_meta_rating: 92.3664,
                    stamina: 78,
                    standing_tackle: 24,
                    strength: 82,
                    vision: 87,
                    volleys: 86,
                    weak_foot: 4,
                    weight: 81,
                    wing_meta_rating: 85.3858
                    },
                    formation: "4231"
                })
            },
            addToFavorites: (name, url) => {
                let newObj = { name: name, url: url}
                setStore({favorites: getStore().favorites.concat(newObj)})
                console.log(getStore().favorites)
            },
            deleteFromFavorites: (name) => {
                let newObj = getStore().favorites.filter( (fav) => fav.name !== name)
                setStore({favorites: newObj})
            }

        }
    };
};

export default getState;