import registerUserAPI from "../services/registerUserAPI";
import loginUserAPI from "../services/loginUserAPI";
import getSquadByLeagueAPI from "../services/getSquadByLeagueAPI";
import getListByLeagueAPI from "../services/getListByLeagueAPI";
import searchPlayerByNameAPI from "../services/searchPlayerByNameAPI";

const getState = ({ getStore, getActions, setStore }) => {
    const backendUrl = 'http://localhost/5000'
    return {
        store: {
            currentUser: null,
            user: {},
            token: {},
            invalidCredentials: false,
            registerFailed: false,
            errorMesage: '',
            registerFormData: {
                username: '',
                email: '',
                password: ''
            },
            loginFormData: {
                username: '',
                password: ''
            },
            error: false,
            searchPlayerResult: [],
            user_formation: '433',
            squadCreator0: {
                position: '',
                player_data: null
            },
            squadCreator1: {
                position: '',
                player_data: null
            },
            squadCreator2: {
                position: '',
                player_data: null
            },
            squadCreator3: {
                position: '',
                player_data: null
            },
            squadCreator4: {
                position: '',
                player_data: null
            },
            squadCreator5: {
                position: '',
                player_data: null
            },
            squadCreator6: {
                position: '',
                player_data: null
            },
            squadCreator7: {
                position: '',
                player_data: null
            },
            squadCreator8: {
                position: '',
                player_data: null
            },
            squadCreator9: {
                position: '',
                player_data: null
            },
            squadCreator10: {
                position: '',
                player_data: null
            },

            plSquad: {},
            l1Squad: {},
            blSquad: {},
            saSquad: {},
            llSquad: {},
            plListAttackers: [],
            plListMidfielders: [],
            plListDefenders: [],
            l1ListAttackers: [],
            l1ListMidfielders: [],
            l1ListDefenders: [],
            blListAttackers: [],
            blListMidfielders: [],
            blListDefenders: [],
            saListAttackers: [],
            saListMidfielders: [],
            saListDefenders: [],
            llListAttackers: [],
            llListMidfielders: [],
            llListDefenders: [],
            face: '',
            PlayerDetailsPlayer: {
                id: 99,
                global_id: 268,
                rarity: 1,
                common_name: "Ronaldo",
                name: "Cristiano Ronaldo",
                first_name: "C. Ronaldo",
                last_name: "Cristiano Ronaldo",
                rating: 91,
                lw_meta_rating: 108.05,
                lf_meta_rating: 102.53,
                lm_meta_rating: 110.74,
                lst_meta_rating: 116.68,
                cst_meta_rating: 117.73,
                rst_meta_rating: 120.68,
                cf_meta_rating: 123.04,
                rw_meta_rating: 105.05,
                rf_meta_rating: 99.53,
                rm_meta_rating: 107.74,
                lcam_meta_rating: 103.96,
                ccam_meta_rating: 105.57,
                rcam_meta_rating: 103.92,
                lcm_meta_rating: 79.89,
                ccm_meta_rating: 81.76,
                rcm_meta_rating: 79.91,
                lcdm_meta_rating: 72.01,
                ccdm_meta_rating: 72.01,
                rcdm_meta_rating: 72.03,
                lwb_meta_rating: 85.56,
                lb_meta_rating: 70.04,
                lcb_meta_rating: 69.29,
                ccb_meta_rating: 69.29,
                rcb_meta_rating: 69.33,
                rwb_meta_rating: 85.6,
                rb_meta_rating: 70.08,
                gk_meta_rating: 27.75,
                nation: 38,
                league: 13,
                club: 11,
                position: "ST",
                height: 187,
                weight: 83,
                attack_work_rate: "High",
                defense_work_rate: "Low",
                foot: "Right",
                weak_foot: 4,
                skill_moves: 5,
                shooting: 93,
                positioning: 95,
                finishing: 95,
                shot_power: 94,
                long_shots: 93,
                volleys: 86,
                penalties: 84,
                defending: 34,
                heading_accuracy: 90,
                interceptions: 29,
                sliding_tackle: 24,
                standing_tackle: 32,
                dribbling_face: 88,
                agility: 86,
                balance: 74,
                ball_control: 88,
                composure: 95,
                dribbling: 88,
                reactions: 94,
                pace: 87,
                acceleration: 85,
                sprint_speed: 88,
                passing: 82,
                crossing: 87,
                curve: 81,
                free_kick_accuracy: 84,
                long_passing: 77,
                short_passing: 80,
                vision: 82,
                physicality: 75,
                aggression: 63,
                stamina: 77,
                jumping: 95,
                strength: 77,
                diving: 0,
                handling: 0,
                kicking: 0,
                gk_positioning: 0,
                reflexes: 0
                }
        },
        actions: {
            registerUser: async (registerFormData, history) => {
                const us = await registerUserAPI(registerFormData).then((data) => {
                    console.log(data)
                      
                    if(data.status == 200) {
                        setStore({...getStore, currentUser: data.user[0]})
                        setStore({...getStore, token: data.token})
                        localStorage.setItem("jwt-token", data.token);
                        //localStorage.setItem("currentUser", data.user[0]);   
                        //history.push('/')
                    } else {
                        setStore({...getStore, errorMesage: data.message}) 
                        history.push("/register")
                    }
                })
            },
            loginUser: async (loginFormData, history) => {
                const us = await loginUserAPI(loginFormData).then((data) => {
                    console.log('data en login flux', data)
                    if(data.status == 200) {
                        setStore({...getStore, currentUser: data.user[0]})
                        //await getActions.getUser(data.token)
                        setStore({...getStore, token: data.token})
                        localStorage.setItem("jwt-token", data.token);
                    } else {
                        setStore({...getStore, invalidCredentials: true})
                        history.push("/home")
                    }
                })
            },
            searchPlayerByName: async (searchData) => {
                const search = await searchPlayerByNameAPI(searchData).then((data) => {
                    console.log('player search result en login flux: ', data)
                    if(data.status == 200) {
                        setStore({...getStore, searchPlayerResult: data.result})
                    } else {
                        setStore({...getStore, errorMesage: data.message})
                        setStore({...getStore, searchPlayerResult: []})
                    }
                })
            },
            addPlayer: (player, position, index) => {
                if (index == 0) {
                    setStore({...getStore, squadCreator0: {'position': position, 'player_data': player}})
                } else if (index == 1) {
                    setStore({...getStore, squadCreator1: {'position': position, 'player_data': player}})
                } else if (index == 2) {
                    setStore({...getStore, squadCreator2: {'position': position, 'player_data': player}})
                } else if (index == 3) {
                    setStore({...getStore, squadCreator3: {'position': position, 'player_data': player}})
                } else if (index == 4) {
                    setStore({...getStore, squadCreator4: {'position': position, 'player_data': player}})
                } else if (index == 5) {
                    setStore({...getStore, squadCreator5: {'position': position, 'player_data': player}})
                } else if (index == 6) {
                    setStore({...getStore, squadCreator6: {'position': position, 'player_data': player}})
                } else if (index == 7) {
                    setStore({...getStore, squadCreator7: {'position': position, 'player_data': player}})
                } else if (index == 8) {
                    setStore({...getStore, squadCreator8: {'position': position, 'player_data': player}})
                } else if (index == 9) {
                    setStore({...getStore, squadCreator9: {'position': position, 'player_data': player}})
                } else if (index == 10) {
                    setStore({...getStore, squadCreator1: {'position': position, 'player_data': player}})
                }
            },
            removePlayer: (position, index) => {
                if (index == 0) {
                    setStore({...getStore, squadCreator0: {'position': position, 'player_data': null}})
                } else if (index == 1) {
                    setStore({...getStore, squadCreator1: {'position': position, 'player_data': null}})
                } else if (index == 2) {
                    setStore({...getStore, squadCreator2: {'position': position, 'player_data': null}})
                } else if (index == 3) {
                    setStore({...getStore, squadCreator3: {'position': position, 'player_data': null}})
                } else if (index == 4) {
                    setStore({...getStore, squadCreator4: {'position': position, 'player_data': null}})
                } else if (index == 5) {
                    setStore({...getStore, squadCreator5: {'position': position, 'player_data': null}})
                } else if (index == 6) {
                    setStore({...getStore, squadCreator6: {'position': position, 'player_data': null}})
                } else if (index == 7) {
                    setStore({...getStore, squadCreator7: {'position': position, 'player_data': null}})
                } else if (index == 8) {
                    setStore({...getStore, squadCreator8: {'position': position, 'player_data': null}})
                } else if (index == 9) {
                    setStore({...getStore, squadCreator9: {'position': position, 'player_data': null}})
                } else if (index == 10) {
                    setStore({...getStore, squadCreator1: {'position': position, 'player_data': null}})
                }
            },

            formationInterpreter: (positions_string) => {
                if(positions_string == '442') {
                    return ["LST", "RST", "LM", "LCM", "RCM", "RM", "LB", "LCB", "RCB", "RB", "GK"]
                } else if(positions_string == '433') {
                    return ["LW", "CST", "RW", "LCM", "CCM", "RCM", "LB", "LCB", "RCB", "RB", "GK"]
                }
            },

            setUserFormation: (user_formation) => {
                setStore({...getStore, user_formation: user_formation})
            },
            // getPlayer: (position) => {
            //     return getStore.selectedPlayer
            // },
            logout: () => {
                setStore({...getStore, currentUser: null})
                setStore({...getStore, token: null})
            },

            getSquadRating: (squad) => {
                let ratingSum = 0
                for(let i = 0; i < squad.length; i++) {
                    ratingSum += squad[i].player_data.rating
                }
                let squadRating = parseInt(ratingSum / 11)  
                return squadRating;
            },
            getSquadPrice: (league) => {
                if(league == 'Premier League') {
                    return 2500000
                } else if(league == 'Ligue 1') {
                    return 3200000
                } else if(league == 'Bundesliga') {
                    return 1200000
                } else if(league == 'Serie A TIM') {
                    return 1000000
                } else if(league == 'LaLiga Santander') {
                    return 1400000
                } else return 0
            },
            // getUser: async (token) => {
            
            // },
            getSquads: async () => {
                const pl = await getSquadByLeagueAPI(13).then((data) => {
                    console.log(data)
                    setStore({...getStore, plSquad: data})
                })
                const l1 = await getSquadByLeagueAPI(16).then((data) => {
                    console.log(data)
                    setStore({...getStore, l1Squad: data})
                })
                const bl = await getSquadByLeagueAPI(19).then((data) => {
                    console.log(data)
                    setStore({...getStore, blSquad: data})
                })
                const sa = await getSquadByLeagueAPI(31).then((data) => {
                    console.log(data)
                    setStore({...getStore, saSquad: data})
                })
                const ll = await getSquadByLeagueAPI(53).then((data) => {
                    console.log(data)
                    setStore({...getStore, llSquad: data})
                })
            },
            getPlayerLists: async () => {
                const pl_list_attackers = await getListByLeagueAPI(13, 'cst').then((data) => {
                    setStore({...getStore, plListAttackers: data})
                })
                const pl_list_midfielders = await getListByLeagueAPI(13, 'ccm').then((data) => {
                    setStore({...getStore, plListMidfielders: data})
                })
                const pl_list_defenders = await getListByLeagueAPI(13, 'ccb').then((data) => {
                    setStore({...getStore, plListDefenders: data})
                })
                const l1_list_attackers = await getListByLeagueAPI(16, 'cst').then((data) => {
                    setStore({...getStore, l1ListAttackers: data})
                }) 
                const l1_list_midfielders = await getListByLeagueAPI(16, 'ccm').then((data) => {
                    setStore({...getStore, l1ListMidfielders: data})
                }) 
                const l1_list_defenders = await getListByLeagueAPI(16, 'ccb').then((data) => {
                    setStore({...getStore, l1ListDefenders: data})
                }) 
                const bl_list_attackers = await getListByLeagueAPI(19, 'cst').then((data) => {
                    setStore({...getStore, blListAttackers: data})
                })
                const bl_list_midfielders = await getListByLeagueAPI(19, 'ccm').then((data) => {
                    setStore({...getStore, blListMidfielders: data})
                })
                const bl_list_defenders = await getListByLeagueAPI(19, 'ccb').then((data) => {
                    setStore({...getStore, blListDefenders: data})
                })
                const sa_list_attackers = await getListByLeagueAPI(31, 'cst').then((data) => {
                    setStore({...getStore, saListAttackers: data})
                })
                const sa_list_midfielders = await getListByLeagueAPI(31, 'ccm').then((data) => {
                    setStore({...getStore, saListMidfielders: data})
                })
                const sa_list_defenders = await getListByLeagueAPI(31, 'ccb').then((data) => {
                    setStore({...getStore, saListDefenders: data})
                })
                const ll_list_attackers = await getListByLeagueAPI(53, 'cst').then((data) => {
                    setStore({...getStore, llListAttackers: data})
                })
                const ll_list_midfielders = await getListByLeagueAPI(53, 'ccm').then((data) => {
                    setStore({...getStore, llListMidfielders: data})
                })
                const ll_list_defenders = await getListByLeagueAPI(53, 'ccb').then((data) => {
                    setStore({...getStore, llListDefenders: data})
                })
            },
            getSquadByLeague: async (league) => {
                const squad = await getSquadByLeagueAPI(league).then((data) => {
                    setStore({...getStore, plSquad: data})
                })   
            },
            setPlayerDetailsPlayer: (player, history) => { 
                console.log('player sent to flux:', player)
                setStore({...getStore, PlayerDetailsPlayer: player})
                history.push("/playerdetails")
                
            },
            getHardCodedPlayerList: () => {
                return({
                    data: [
                    {
                    id: 99,
                    global_id: 268,
                    rarity: 1,
                    common_name: "Ronaldo",
                    name: "Cristiano Ronaldo",
                    first_name: "C. Ronaldo",
                    last_name: "Cristiano Ronaldo",
                    rating: 91,
                    lw_meta_rating: 108.05,
                    lf_meta_rating: 102.53,
                    lm_meta_rating: 110.74,
                    lst_meta_rating: 116.68,
                    cst_meta_rating: 117.73,
                    rst_meta_rating: 120.68,
                    cf_meta_rating: 123.04,
                    rw_meta_rating: 105.05,
                    rf_meta_rating: 99.53,
                    rm_meta_rating: 107.74,
                    lcam_meta_rating: 103.96,
                    ccam_meta_rating: 105.57,
                    rcam_meta_rating: 103.92,
                    lcm_meta_rating: 79.89,
                    ccm_meta_rating: 81.76,
                    rcm_meta_rating: 79.91,
                    lcdm_meta_rating: 72.01,
                    ccdm_meta_rating: 72.01,
                    rcdm_meta_rating: 72.03,
                    lwb_meta_rating: 85.56,
                    lb_meta_rating: 70.04,
                    lcb_meta_rating: 69.29,
                    ccb_meta_rating: 69.29,
                    rcb_meta_rating: 69.33,
                    rwb_meta_rating: 85.6,
                    rb_meta_rating: 70.08,
                    gk_meta_rating: 27.75,
                    nation: 38,
                    league: 13,
                    club: 11,
                    position: "ST",
                    height: 187,
                    weight: 83,
                    attack_work_rate: "High",
                    defense_work_rate: "Low",
                    foot: "Right",
                    weak_foot: 4,
                    skill_moves: 5,
                    shooting: 93,
                    positioning: 95,
                    finishing: 95,
                    shot_power: 94,
                    long_shots: 93,
                    volleys: 86,
                    penalties: 84,
                    defending: 34,
                    heading_accuracy: 90,
                    interceptions: 29,
                    sliding_tackle: 24,
                    standing_tackle: 32,
                    dribbling_face: 88,
                    agility: 86,
                    balance: 74,
                    ball_control: 88,
                    composure: 95,
                    dribbling: 88,
                    reactions: 94,
                    pace: 87,
                    acceleration: 85,
                    sprint_speed: 88,
                    passing: 82,
                    crossing: 87,
                    curve: 81,
                    free_kick_accuracy: 84,
                    long_passing: 77,
                    short_passing: 80,
                    vision: 82,
                    physicality: 75,
                    aggression: 63,
                    stamina: 77,
                    jumping: 95,
                    strength: 77,
                    diving: 0,
                    handling: 0,
                    kicking: 0,
                    gk_positioning: 0,
                    reflexes: 0
                    },
                    {
                    id: 60,
                    global_id: 206,
                    rarity: 1,
                    common_name: "Mané",
                    name: "Sadio Mané",
                    first_name: "Sadio",
                    last_name: "Sadio Mané",
                    rating: 89,
                    lw_meta_rating: 110.7,
                    lf_meta_rating: 105.81,
                    lm_meta_rating: 113.01,
                    lst_meta_rating: 109.46,
                    cst_meta_rating: 110.18,
                    rst_meta_rating: 113.46,
                    cf_meta_rating: 115.43,
                    rw_meta_rating: 103.7,
                    rf_meta_rating: 98.81,
                    rm_meta_rating: 106.01,
                    lcam_meta_rating: 102.79,
                    ccam_meta_rating: 104.08,
                    rcam_meta_rating: 102.75,
                    lcm_meta_rating: 79.83,
                    ccm_meta_rating: 81.58,
                    rcm_meta_rating: 79.85,
                    lcdm_meta_rating: 74.23,
                    ccdm_meta_rating: 74.23,
                    rcdm_meta_rating: 74.25,
                    lwb_meta_rating: 89.99,
                    lb_meta_rating: 73.85,
                    lcb_meta_rating: 72.58,
                    ccb_meta_rating: 72.58,
                    rcb_meta_rating: 72.62,
                    rwb_meta_rating: 90.03,
                    rb_meta_rating: 73.89,
                    gk_meta_rating: 27.53,
                    nation: 136,
                    league: 13,
                    club: 9,
                    position: "LW",
                    height: 175,
                    weight: 69,
                    attack_work_rate: "High",
                    defense_work_rate: "Med",
                    foot: "Right",
                    weak_foot: 4,
                    skill_moves: 4,
                    shooting: 83,
                    positioning: 90,
                    finishing: 86,
                    shot_power: 83,
                    long_shots: 80,
                    volleys: 75,
                    penalties: 71,
                    defending: 44,
                    heading_accuracy: 84,
                    interceptions: 35,
                    sliding_tackle: 38,
                    standing_tackle: 42,
                    dribbling_face: 89,
                    agility: 93,
                    balance: 88,
                    ball_control: 88,
                    composure: 84,
                    dribbling: 90,
                    reactions: 91,
                    pace: 91,
                    acceleration: 93,
                    sprint_speed: 90,
                    passing: 80,
                    crossing: 78,
                    curve: 77,
                    free_kick_accuracy: 64,
                    long_passing: 71,
                    short_passing: 84,
                    vision: 84,
                    physicality: 77,
                    aggression: 75,
                    stamina: 85,
                    jumping: 87,
                    strength: 72,
                    diving: 0,
                    handling: 0,
                    kicking: 0,
                    gk_positioning: 0,
                    reflexes: 0
                    },
                    {
                    id: 68,
                    global_id: 214,
                    rarity: 1,
                    common_name: "Firmino",
                    name: "Roberto Firmino",
                    first_name: "Roberto Firmino",
                    last_name: "Roberto Firmino",
                    rating: 85,
                    lw_meta_rating: 101.81,
                    lf_meta_rating: 96.92,
                    lm_meta_rating: 104.36,
                    lst_meta_rating: 109.08,
                    cst_meta_rating: 109.92,
                    rst_meta_rating: 113.08,
                    cf_meta_rating: 115.6,
                    rw_meta_rating: 98.81,
                    rf_meta_rating: 93.92,
                    rm_meta_rating: 101.36,
                    lcam_meta_rating: 97.72,
                    ccam_meta_rating: 102.72,
                    rcam_meta_rating: 97.68,
                    lcm_meta_rating: 79.84,
                    ccm_meta_rating: 81.65,
                    rcm_meta_rating: 79.86,
                    lcdm_meta_rating: 78.48,
                    ccdm_meta_rating: 78.48,
                    rcdm_meta_rating: 78.5,
                    lwb_meta_rating: 90.45,
                    lb_meta_rating: 77.12,
                    lcb_meta_rating: 75.05,
                    ccb_meta_rating: 75.05,
                    rcb_meta_rating: 75.09,
                    rwb_meta_rating: 90.49,
                    rb_meta_rating: 77.16,
                    gk_meta_rating: 26.64,
                    nation: 54,
                    league: 13,
                    club: 9,
                    position: "CF",
                    height: 181,
                    weight: 76,
                    attack_work_rate: "High",
                    defense_work_rate: "High",
                    foot: "Right",
                    weak_foot: 4,
                    skill_moves: 5,
                    shooting: 78,
                    positioning: 82,
                    finishing: 78,
                    shot_power: 79,
                    long_shots: 76,
                    volleys: 83,
                    penalties: 72,
                    defending: 59,
                    heading_accuracy: 78,
                    interceptions: 58,
                    sliding_tackle: 42,
                    standing_tackle: 64,
                    dribbling_face: 89,
                    agility: 85,
                    balance: 86,
                    ball_control: 90,
                    composure: 88,
                    dribbling: 89,
                    reactions: 86,
                    pace: 77,
                    acceleration: 77,
                    sprint_speed: 77,
                    passing: 79,
                    crossing: 73,
                    curve: 81,
                    free_kick_accuracy: 65,
                    long_passing: 76,
                    short_passing: 84,
                    vision: 83,
                    physicality: 78,
                    aggression: 75,
                    stamina: 87,
                    jumping: 81,
                    strength: 74,
                    diving: 0,
                    handling: 0,
                    kicking: 0,
                    gk_positioning: 0,
                    reflexes: 0
                    },
                    {
                    id: 136,
                    global_id: 449,
                    rarity: 1,
                    common_name: "Kane",
                    name: "Harry Kane",
                    first_name: "Harry",
                    last_name: "Harry Kane",
                    rating: 90,
                    lw_meta_rating: 98.84,
                    lf_meta_rating: 94.1,
                    lm_meta_rating: 100.84,
                    lst_meta_rating: 108.79,
                    cst_meta_rating: 109.83,
                    rst_meta_rating: 112.79,
                    cf_meta_rating: 115.71,
                    rw_meta_rating: 95.84,
                    rf_meta_rating: 91.1,
                    rm_meta_rating: 97.84,
                    lcam_meta_rating: 95.03,
                    ccam_meta_rating: 102.24,
                    rcam_meta_rating: 94.99,
                    lcm_meta_rating: 80.58,
                    ccm_meta_rating: 82.46,
                    rcm_meta_rating: 80.6,
                    lcdm_meta_rating: 73.78,
                    ccdm_meta_rating: 73.78,
                    rcdm_meta_rating: 73.8,
                    lwb_meta_rating: 81.3,
                    lb_meta_rating: 67.73,
                    lcb_meta_rating: 70,
                    ccb_meta_rating: 70,
                    rcb_meta_rating: 70.04,
                    rwb_meta_rating: 81.34,
                    rb_meta_rating: 67.77,
                    gk_meta_rating: 26.77,
                    nation: 14,
                    league: 13,
                    club: 18,
                    position: "ST",
                    height: 188,
                    weight: 89,
                    attack_work_rate: "High",
                    defense_work_rate: "High",
                    foot: "Right",
                    weak_foot: 5,
                    skill_moves: 3,
                    shooting: 91,
                    positioning: 94,
                    finishing: 94,
                    shot_power: 91,
                    long_shots: 86,
                    volleys: 88,
                    penalties: 91,
                    defending: 47,
                    heading_accuracy: 86,
                    interceptions: 44,
                    sliding_tackle: 38,
                    standing_tackle: 36,
                    dribbling_face: 83,
                    agility: 71,
                    balance: 70,
                    ball_control: 85,
                    composure: 91,
                    dribbling: 83,
                    reactions: 92,
                    pace: 70,
                    acceleration: 65,
                    sprint_speed: 74,
                    passing: 83,
                    crossing: 80,
                    curve: 83,
                    free_kick_accuracy: 65,
                    long_passing: 86,
                    short_passing: 85,
                    vision: 87,
                    physicality: 83,
                    aggression: 80,
                    stamina: 83,
                    jumping: 79,
                    strength: 85,
                    diving: 0,
                    handling: 0,
                    kicking: 0,
                    gk_positioning: 0,
                    reflexes: 0
                    },
                    {
                    id: 43,
                    global_id: 151,
                    rarity: 1,
                    common_name: "Richarlison",
                    name: "Richarlison de Andrade",
                    first_name: "Richarlison",
                    last_name: "Richarlison de Andrade",
                    rating: 82,
                    lw_meta_rating: 100.63,
                    lf_meta_rating: 95.98,
                    lm_meta_rating: 103.04,
                    lst_meta_rating: 108.75,
                    cst_meta_rating: 109.73,
                    rst_meta_rating: 112.75,
                    cf_meta_rating: 114.65,
                    rw_meta_rating: 97.63,
                    rf_meta_rating: 92.98,
                    rm_meta_rating: 100.04,
                    lcam_meta_rating: 96.75,
                    ccam_meta_rating: 97.95,
                    rcam_meta_rating: 96.71,
                    lcm_meta_rating: 75.59,
                    ccm_meta_rating: 77.4,
                    rcm_meta_rating: 75.61,
                    lcdm_meta_rating: 76.17,
                    ccdm_meta_rating: 76.17,
                    rcdm_meta_rating: 76.19,
                    lwb_meta_rating: 87.51,
                    lb_meta_rating: 74.36,
                    lcb_meta_rating: 74.84,
                    ccb_meta_rating: 74.84,
                    rcb_meta_rating: 74.88,
                    rwb_meta_rating: 87.55,
                    rb_meta_rating: 74.4,
                    gk_meta_rating: 26.34,
                    nation: 54,
                    league: 13,
                    club: 7,
                    position: "ST",
                    height: 181,
                    weight: 71,
                    attack_work_rate: "High",
                    defense_work_rate: "Med",
                    foot: "Right",
                    weak_foot: 5,
                    skill_moves: 4,
                    shooting: 78,
                    positioning: 83,
                    finishing: 80,
                    shot_power: 83,
                    long_shots: 70,
                    volleys: 75,
                    penalties: 77,
                    defending: 53,
                    heading_accuracy: 83,
                    interceptions: 46,
                    sliding_tackle: 48,
                    standing_tackle: 58,
                    dribbling_face: 83,
                    agility: 79,
                    balance: 73,
                    ball_control: 83,
                    composure: 81,
                    dribbling: 86,
                    reactions: 82,
                    pace: 83,
                    acceleration: 85,
                    sprint_speed: 81,
                    passing: 73,
                    crossing: 73,
                    curve: 74,
                    free_kick_accuracy: 65,
                    long_passing: 61,
                    short_passing: 79,
                    vision: 74,
                    physicality: 80,
                    aggression: 84,
                    stamina: 83,
                    jumping: 86,
                    strength: 77,
                    diving: 0,
                    handling: 0,
                    kicking: 0,
                    gk_positioning: 0,
                    reflexes: 0
                    },
                    {
                    id: 1,
                    global_id: 1,
                    rarity: 1,
                    common_name: "Aubameyang",
                    name: "Aubameyang",
                    first_name: "Pierre-Emerick",
                    last_name: "Aubameyang",
                    rating: 85,
                    lw_meta_rating: 100.07,
                    lf_meta_rating: 95.6,
                    lm_meta_rating: 101.98,
                    lst_meta_rating: 108.74,
                    cst_meta_rating: 109.39,
                    rst_meta_rating: 112.74,
                    cf_meta_rating: 114.35,
                    rw_meta_rating: 97.07,
                    rf_meta_rating: 92.6,
                    rm_meta_rating: 98.98,
                    lcam_meta_rating: 96.31,
                    ccam_meta_rating: 97.41,
                    rcam_meta_rating: 96.27,
                    lcm_meta_rating: 73.79,
                    ccm_meta_rating: 75.66,
                    rcm_meta_rating: 73.81,
                    lcdm_meta_rating: 66.76,
                    ccdm_meta_rating: 66.76,
                    rcdm_meta_rating: 66.78,
                    lwb_meta_rating: 84.15,
                    lb_meta_rating: 70.34,
                    lcb_meta_rating: 68.41,
                    ccb_meta_rating: 68.41,
                    rcb_meta_rating: 68.45,
                    rwb_meta_rating: 84.19,
                    rb_meta_rating: 70.38,
                    gk_meta_rating: 27.3,
                    nation: 115,
                    league: 13,
                    club: 1,
                    position: "ST",
                    height: 187,
                    weight: 80,
                    attack_work_rate: "Med",
                    defense_work_rate: "Low",
                    foot: "Right",
                    weak_foot: 4,
                    skill_moves: 4,
                    shooting: 85,
                    positioning: 90,
                    finishing: 89,
                    shot_power: 82,
                    long_shots: 78,
                    volleys: 83,
                    penalties: 83,
                    defending: 35,
                    heading_accuracy: 73,
                    interceptions: 48,
                    sliding_tackle: 36,
                    standing_tackle: 29,
                    dribbling_face: 80,
                    agility: 77,
                    balance: 67,
                    ball_control: 81,
                    composure: 87,
                    dribbling: 79,
                    reactions: 86,
                    pace: 89,
                    acceleration: 87,
                    sprint_speed: 91,
                    passing: 75,
                    crossing: 76,
                    curve: 81,
                    free_kick_accuracy: 76,
                    long_passing: 64,
                    short_passing: 77,
                    vision: 77,
                    physicality: 69,
                    aggression: 43,
                    stamina: 79,
                    jumping: 75,
                    strength: 74,
                    diving: 0,
                    handling: 0,
                    kicking: 0,
                    gk_positioning: 0,
                    reflexes: 0
                    },
                    {
                    id: 63,
                    global_id: 209,
                    rarity: 1,
                    common_name: "Salah",
                    name: "Mohamed Salah",
                    first_name: "Mohamed",
                    last_name: "Mohamed Salah",
                    rating: 89,
                    lw_meta_rating: 101.58,
                    lf_meta_rating: 97.2,
                    lm_meta_rating: 103.38,
                    lst_meta_rating: 107.94,
                    cst_meta_rating: 108.32,
                    rst_meta_rating: 107.9,
                    cf_meta_rating: 114.11,
                    rw_meta_rating: 108.58,
                    rf_meta_rating: 101.24,
                    rm_meta_rating: 111.38,
                    lcam_meta_rating: 101.03,
                    ccam_meta_rating: 103.62,
                    rcam_meta_rating: 101.07,
                    lcm_meta_rating: 78.89,
                    ccm_meta_rating: 80.62,
                    rcm_meta_rating: 78.87,
                    lcdm_meta_rating: 73.49,
                    ccdm_meta_rating: 73.47,
                    rcdm_meta_rating: 73.47,
                    lwb_meta_rating: 90.81,
                    lb_meta_rating: 75.64,
                    lcb_meta_rating: 73.55,
                    ccb_meta_rating: 73.51,
                    rcb_meta_rating: 73.51,
                    rwb_meta_rating: 90.77,
                    rb_meta_rating: 75.6,
                    gk_meta_rating: 27.54,
                    nation: 111,
                    league: 13,
                    club: 9,
                    position: "RW",
                    height: 175,
                    weight: 71,
                    attack_work_rate: "High",
                    defense_work_rate: "Med",
                    foot: "Left",
                    weak_foot: 3,
                    skill_moves: 4,
                    shooting: 87,
                    positioning: 91,
                    finishing: 91,
                    shot_power: 82,
                    long_shots: 84,
                    volleys: 81,
                    penalties: 86,
                    defending: 45,
                    heading_accuracy: 59,
                    interceptions: 55,
                    sliding_tackle: 41,
                    standing_tackle: 43,
                    dribbling_face: 90,
                    agility: 91,
                    balance: 91,
                    ball_control: 89,
                    composure: 90,
                    dribbling: 90,
                    reactions: 92,
                    pace: 90,
                    acceleration: 89,
                    sprint_speed: 91,
                    passing: 81,
                    crossing: 79,
                    curve: 83,
                    free_kick_accuracy: 69,
                    long_passing: 75,
                    short_passing: 84,
                    vision: 83,
                    physicality: 75,
                    aggression: 63,
                    stamina: 85,
                    jumping: 69,
                    strength: 75,
                    diving: 0,
                    handling: 0,
                    kicking: 0,
                    gk_positioning: 0,
                    reflexes: 0
                    },
                    {
                    id: 137,
                    global_id: 450,
                    rarity: 1,
                    common_name: "Son",
                    name: "Heung Min Son",
                    first_name: "Heung Min",
                    last_name: "Heung Min Son",
                    rating: 89,
                    lw_meta_rating: 108.85,
                    lf_meta_rating: 104.56,
                    lm_meta_rating: 110.52,
                    lst_meta_rating: 108.24,
                    cst_meta_rating: 108.31,
                    rst_meta_rating: 112.24,
                    cf_meta_rating: 114.36,
                    rw_meta_rating: 101.85,
                    rf_meta_rating: 97.56,
                    rm_meta_rating: 103.52,
                    lcam_meta_rating: 101.34,
                    ccam_meta_rating: 105.32,
                    rcam_meta_rating: 101.3,
                    lcm_meta_rating: 78.33,
                    ccm_meta_rating: 80.16,
                    rcm_meta_rating: 78.35,
                    lcdm_meta_rating: 69.28,
                    ccdm_meta_rating: 69.28,
                    rcdm_meta_rating: 69.3,
                    lwb_meta_rating: 88.13,
                    lb_meta_rating: 72.68,
                    lcb_meta_rating: 66.64,
                    ccb_meta_rating: 66.64,
                    rcb_meta_rating: 66.68,
                    rwb_meta_rating: 88.17,
                    rb_meta_rating: 72.72,
                    gk_meta_rating: 27.73,
                    nation: 167,
                    league: 13,
                    club: 18,
                    position: "LM",
                    height: 183,
                    weight: 78,
                    attack_work_rate: "High",
                    defense_work_rate: "High",
                    foot: "Right",
                    weak_foot: 5,
                    skill_moves: 4,
                    shooting: 87,
                    positioning: 91,
                    finishing: 88,
                    shot_power: 88,
                    long_shots: 89,
                    volleys: 78,
                    penalties: 73,
                    defending: 43,
                    heading_accuracy: 68,
                    interceptions: 39,
                    sliding_tackle: 33,
                    standing_tackle: 34,
                    dribbling_face: 86,
                    agility: 86,
                    balance: 78,
                    ball_control: 84,
                    composure: 89,
                    dribbling: 87,
                    reactions: 91,
                    pace: 88,
                    acceleration: 85,
                    sprint_speed: 90,
                    passing: 82,
                    crossing: 83,
                    curve: 85,
                    free_kick_accuracy: 74,
                    long_passing: 74,
                    short_passing: 84,
                    vision: 83,
                    physicality: 69,
                    aggression: 62,
                    stamina: 88,
                    jumping: 60,
                    strength: 64,
                    diving: 0,
                    handling: 0,
                    kicking: 0,
                    gk_positioning: 0,
                    reflexes: 0
                    },
                    {
                    id: 22,
                    global_id: 116,
                    rarity: 1,
                    common_name: "Lukaku",
                    name: "Romelu Lukaku",
                    first_name: "Romelu",
                    last_name: "Romelu Lukaku",
                    rating: 88,
                    lw_meta_rating: 91.99,
                    lf_meta_rating: 87.76,
                    lm_meta_rating: 93.77,
                    lst_meta_rating: 107.2,
                    cst_meta_rating: 108.27,
                    rst_meta_rating: 107.16,
                    cf_meta_rating: 112.91,
                    rw_meta_rating: 94.99,
                    rf_meta_rating: 87.8,
                    rm_meta_rating: 97.77,
                    lcam_meta_rating: 91.4,
                    ccam_meta_rating: 94.29,
                    rcam_meta_rating: 91.44,
                    lcm_meta_rating: 73.1,
                    ccm_meta_rating: 74.99,
                    rcm_meta_rating: 73.08,
                    lcdm_meta_rating: 69.47,
                    ccdm_meta_rating: 69.45,
                    rcdm_meta_rating: 69.45,
                    lwb_meta_rating: 78.96,
                    lb_meta_rating: 65.68,
                    lcb_meta_rating: 69.84,
                    ccb_meta_rating: 69.8,
                    rcb_meta_rating: 69.8,
                    rwb_meta_rating: 78.92,
                    rb_meta_rating: 65.64,
                    gk_meta_rating: 27.28,
                    nation: 7,
                    league: 13,
                    club: 5,
                    position: "ST",
                    height: 191,
                    weight: 94,
                    attack_work_rate: "Med",
                    defense_work_rate: "Med",
                    foot: "Left",
                    weak_foot: 4,
                    skill_moves: 3,
                    shooting: 87,
                    positioning: 89,
                    finishing: 92,
                    shot_power: 89,
                    long_shots: 74,
                    volleys: 78,
                    penalties: 88,
                    defending: 39,
                    heading_accuracy: 89,
                    interceptions: 27,
                    sliding_tackle: 30,
                    standing_tackle: 41,
                    dribbling_face: 78,
                    agility: 60,
                    balance: 52,
                    ball_control: 77,
                    composure: 86,
                    dribbling: 83,
                    reactions: 91,
                    pace: 84,
                    acceleration: 81,
                    sprint_speed: 87,
                    passing: 74,
                    crossing: 73,
                    curve: 78,
                    free_kick_accuracy: 66,
                    long_passing: 70,
                    short_passing: 77,
                    vision: 75,
                    physicality: 83,
                    aggression: 71,
                    stamina: 71,
                    jumping: 76,
                    strength: 95,
                    diving: 0,
                    handling: 0,
                    kicking: 0,
                    gk_positioning: 0,
                    reflexes: 0
                    },
                    {
                    id: 92,
                    global_id: 253,
                    rarity: 1,
                    common_name: "Jesus",
                    name: "Gabriel Jesus",
                    first_name: "Gabriel",
                    last_name: "Gabriel Jesus",
                    rating: 83,
                    lw_meta_rating: 100.18,
                    lf_meta_rating: 95.98,
                    lm_meta_rating: 101.98,
                    lst_meta_rating: 107.51,
                    cst_meta_rating: 108.18,
                    rst_meta_rating: 111.51,
                    cf_meta_rating: 113.23,
                    rw_meta_rating: 97.18,
                    rf_meta_rating: 92.98,
                    rm_meta_rating: 98.98,
                    lcam_meta_rating: 96.8,
                    ccam_meta_rating: 97.43,
                    rcam_meta_rating: 96.76,
                    lcm_meta_rating: 74.22,
                    ccm_meta_rating: 75.97,
                    rcm_meta_rating: 74.24,
                    lcdm_meta_rating: 68.28,
                    ccdm_meta_rating: 68.28,
                    rcdm_meta_rating: 68.3,
                    lwb_meta_rating: 83.24,
                    lb_meta_rating: 67.67,
                    lcb_meta_rating: 65.74,
                    ccb_meta_rating: 65.74,
                    rcb_meta_rating: 65.78,
                    rwb_meta_rating: 83.28,
                    rb_meta_rating: 67.71,
                    gk_meta_rating: 26.21,
                    nation: 54,
                    league: 13,
                    club: 10,
                    position: "ST",
                    height: 175,
                    weight: 73,
                    attack_work_rate: "High",
                    defense_work_rate: "Med",
                    foot: "Right",
                    weak_foot: 3,
                    skill_moves: 4,
                    shooting: 81,
                    positioning: 87,
                    finishing: 84,
                    shot_power: 82,
                    long_shots: 76,
                    volleys: 77,
                    penalties: 75,
                    defending: 39,
                    heading_accuracy: 77,
                    interceptions: 32,
                    sliding_tackle: 28,
                    standing_tackle: 30,
                    dribbling_face: 86,
                    agility: 91,
                    balance: 87,
                    ball_control: 86,
                    composure: 79,
                    dribbling: 86,
                    reactions: 86,
                    pace: 84,
                    acceleration: 87,
                    sprint_speed: 82,
                    passing: 72,
                    crossing: 66,
                    curve: 76,
                    free_kick_accuracy: 54,
                    long_passing: 66,
                    short_passing: 77,
                    vision: 77,
                    physicality: 73,
                    aggression: 73,
                    stamina: 79,
                    jumping: 79,
                    strength: 69,
                    diving: 0,
                    handling: 0,
                    kicking: 0,
                    gk_positioning: 0,
                    reflexes: 0
                    }
                    ]
                    }

                )
            },
            getHardCodedSquad: () => {
                return ({
                    lst: {
                    id: 99,
                    resource_id: 20801,
                    rarity: 1,
                    common_name: "Ronaldo",
                    name: "Cristiano Ronaldo",
                    first_name: "C. Ronaldo",
                    last_name: "Cristiano Ronaldo",
                    rating: 91,
                    lw_meta_rating: 108.05,
                    lf_meta_rating: 102.53,
                    lm_meta_rating: 110.74,
                    lst_meta_rating: 116.68,
                    cst_meta_rating: 117.73,
                    rst_meta_rating: 120.68,
                    cf_meta_rating: 123.04,
                    rw_meta_rating: 105.05,
                    rf_meta_rating: 99.53,
                    rm_meta_rating: 107.74,
                    lcam_meta_rating: 103.96,
                    ccam_meta_rating: 105.57,
                    rcam_meta_rating: 103.92,
                    lcm_meta_rating: 79.89,
                    ccm_meta_rating: 81.76,
                    rcm_meta_rating: 79.91,
                    lcdm_meta_rating: 72.01,
                    ccdm_meta_rating: 72.01,
                    rcdm_meta_rating: 72.03,
                    lwb_meta_rating: 85.56,
                    lb_meta_rating: 70.04,
                    lcb_meta_rating: 69.29,
                    ccb_meta_rating: 69.29,
                    rcb_meta_rating: 69.33,
                    rwb_meta_rating: 85.6,
                    rb_meta_rating: 70.08,
                    gk_meta_rating: 27.75,
                    nation: 38,
                    league: 13,
                    club: 11,
                    position: "ST",
                    height: 187,
                    weight: 83,
                    attack_work_rate: "High",
                    defense_work_rate: "Low",
                    foot: "Right",
                    weak_foot: 4,
                    skill_moves: 5,
                    shooting: 93,
                    positioning: 95,
                    finishing: 95,
                    shot_power: 94,
                    long_shots: 93,
                    volleys: 86,
                    penalties: 84,
                    defending: 34,
                    heading_accuracy: 90,
                    interceptions: 29,
                    sliding_tackle: 24,
                    standing_tackle: 32,
                    dribbling_face: 88,
                    agility: 86,
                    balance: 74,
                    ball_control: 88,
                    composure: 95,
                    dribbling: 88,
                    reactions: 94,
                    pace: 87,
                    acceleration: 85,
                    sprint_speed: 88,
                    passing: 82,
                    crossing: 87,
                    curve: 81,
                    free_kick_accuracy: 84,
                    long_passing: 77,
                    short_passing: 80,
                    vision: 82,
                    physicality: 75,
                    aggression: 63,
                    stamina: 77,
                    jumping: 95,
                    strength: 77,
                    diving: 0,
                    handling: 0,
                    kicking: 0,
                    gk_positioning: 0,
                    reflexes: 0
                    },
                    rst: {
                    id: 60,
                    resource_id: 208722,
                    rarity: 1,
                    common_name: "Mané",
                    name: "Sadio Mané",
                    first_name: "Sadio",
                    last_name: "Sadio Mané",
                    rating: 89,
                    lw_meta_rating: 110.7,
                    lf_meta_rating: 105.81,
                    lm_meta_rating: 113.01,
                    lst_meta_rating: 109.46,
                    cst_meta_rating: 110.18,
                    rst_meta_rating: 113.46,
                    cf_meta_rating: 115.43,
                    rw_meta_rating: 103.7,
                    rf_meta_rating: 98.81,
                    rm_meta_rating: 106.01,
                    lcam_meta_rating: 102.79,
                    ccam_meta_rating: 104.08,
                    rcam_meta_rating: 102.75,
                    lcm_meta_rating: 79.83,
                    ccm_meta_rating: 81.58,
                    rcm_meta_rating: 79.85,
                    lcdm_meta_rating: 74.23,
                    ccdm_meta_rating: 74.23,
                    rcdm_meta_rating: 74.25,
                    lwb_meta_rating: 89.99,
                    lb_meta_rating: 73.85,
                    lcb_meta_rating: 72.58,
                    ccb_meta_rating: 72.58,
                    rcb_meta_rating: 72.62,
                    rwb_meta_rating: 90.03,
                    rb_meta_rating: 73.89,
                    gk_meta_rating: 27.53,
                    nation: 136,
                    league: 13,
                    club: 9,
                    position: "LW",
                    height: 175,
                    weight: 69,
                    attack_work_rate: "High",
                    defense_work_rate: "Med",
                    foot: "Right",
                    weak_foot: 4,
                    skill_moves: 4,
                    shooting: 83,
                    positioning: 90,
                    finishing: 86,
                    shot_power: 83,
                    long_shots: 80,
                    volleys: 75,
                    penalties: 71,
                    defending: 44,
                    heading_accuracy: 84,
                    interceptions: 35,
                    sliding_tackle: 38,
                    standing_tackle: 42,
                    dribbling_face: 89,
                    agility: 93,
                    balance: 88,
                    ball_control: 88,
                    composure: 84,
                    dribbling: 90,
                    reactions: 91,
                    pace: 91,
                    acceleration: 93,
                    sprint_speed: 90,
                    passing: 80,
                    crossing: 78,
                    curve: 77,
                    free_kick_accuracy: 64,
                    long_passing: 71,
                    short_passing: 84,
                    vision: 84,
                    physicality: 77,
                    aggression: 75,
                    stamina: 85,
                    jumping: 87,
                    strength: 72,
                    diving: 0,
                    handling: 0,
                    kicking: 0,
                    gk_positioning: 0,
                    reflexes: 0
                    },
                    lm: {
                    id: 137,
                    resource_id: 200104,
                    rarity: 1,
                    common_name: "Son",
                    name: "Heung Min Son",
                    first_name: "Heung Min",
                    last_name: "Heung Min Son",
                    rating: 89,
                    lw_meta_rating: 108.85,
                    lf_meta_rating: 104.56,
                    lm_meta_rating: 110.52,
                    lst_meta_rating: 108.24,
                    cst_meta_rating: 108.31,
                    rst_meta_rating: 112.24,
                    cf_meta_rating: 114.36,
                    rw_meta_rating: 101.85,
                    rf_meta_rating: 97.56,
                    rm_meta_rating: 103.52,
                    lcam_meta_rating: 101.34,
                    ccam_meta_rating: 105.32,
                    rcam_meta_rating: 101.3,
                    lcm_meta_rating: 78.33,
                    ccm_meta_rating: 80.16,
                    rcm_meta_rating: 78.35,
                    lcdm_meta_rating: 69.28,
                    ccdm_meta_rating: 69.28,
                    rcdm_meta_rating: 69.3,
                    lwb_meta_rating: 88.13,
                    lb_meta_rating: 72.68,
                    lcb_meta_rating: 66.64,
                    ccb_meta_rating: 66.64,
                    rcb_meta_rating: 66.68,
                    rwb_meta_rating: 88.17,
                    rb_meta_rating: 72.72,
                    gk_meta_rating: 27.73,
                    nation: 167,
                    league: 13,
                    club: 18,
                    position: "LM",
                    height: 183,
                    weight: 78,
                    attack_work_rate: "High",
                    defense_work_rate: "High",
                    foot: "Right",
                    weak_foot: 5,
                    skill_moves: 4,
                    shooting: 87,
                    positioning: 91,
                    finishing: 88,
                    shot_power: 88,
                    long_shots: 89,
                    volleys: 78,
                    penalties: 73,
                    defending: 43,
                    heading_accuracy: 68,
                    interceptions: 39,
                    sliding_tackle: 33,
                    standing_tackle: 34,
                    dribbling_face: 86,
                    agility: 86,
                    balance: 78,
                    ball_control: 84,
                    composure: 89,
                    dribbling: 87,
                    reactions: 91,
                    pace: 88,
                    acceleration: 85,
                    sprint_speed: 90,
                    passing: 82,
                    crossing: 83,
                    curve: 85,
                    free_kick_accuracy: 74,
                    long_passing: 74,
                    short_passing: 84,
                    vision: 83,
                    physicality: 69,
                    aggression: 62,
                    stamina: 88,
                    jumping: 60,
                    strength: 64,
                    diving: 0,
                    handling: 0,
                    kicking: 0,
                    gk_positioning: 0,
                    reflexes: 0
                    },
                    lcm: {
                    id: 21,
                    resource_id: 215914,
                    rarity: 1,
                    common_name: "Kanté",
                    name: "N'Golo Kanté",
                    first_name: "N'Golo",
                    last_name: "N'Golo Kanté",
                    rating: 90,
                    lw_meta_rating: 91.8,
                    lf_meta_rating: 87,
                    lm_meta_rating: 94.6,
                    lst_meta_rating: 94.11,
                    cst_meta_rating: 94.92,
                    rst_meta_rating: 98.11,
                    cf_meta_rating: 99.93,
                    rw_meta_rating: 88.8,
                    rf_meta_rating: 84,
                    rm_meta_rating: 91.6,
                    lcam_meta_rating: 87.51,
                    ccam_meta_rating: 94.27,
                    rcam_meta_rating: 87.47,
                    lcm_meta_rating: 77.05,
                    ccm_meta_rating: 78.73,
                    rcm_meta_rating: 77.07,
                    lcdm_meta_rating: 87.3,
                    ccdm_meta_rating: 87.3,
                    rcdm_meta_rating: 87.32,
                    lwb_meta_rating: 92.93,
                    lb_meta_rating: 81.9,
                    lcb_meta_rating: 90.32,
                    ccb_meta_rating: 90.32,
                    rcb_meta_rating: 90.36,
                    rwb_meta_rating: 92.97,
                    rb_meta_rating: 81.94,
                    gk_meta_rating: 26.01,
                    nation: 18,
                    league: 13,
                    club: 5,
                    position: "CDM",
                    height: 168,
                    weight: 70,
                    attack_work_rate: "Med",
                    defense_work_rate: "High",
                    foot: "Right",
                    weak_foot: 3,
                    skill_moves: 2,
                    shooting: 66,
                    positioning: 72,
                    finishing: 65,
                    shot_power: 71,
                    long_shots: 65,
                    volleys: 56,
                    penalties: 54,
                    defending: 87,
                    heading_accuracy: 54,
                    interceptions: 91,
                    sliding_tackle: 86,
                    standing_tackle: 93,
                    dribbling_face: 82,
                    agility: 82,
                    balance: 92,
                    ball_control: 81,
                    composure: 84,
                    dribbling: 79,
                    reactions: 93,
                    pace: 78,
                    acceleration: 82,
                    sprint_speed: 75,
                    passing: 75,
                    crossing: 68,
                    curve: 49,
                    free_kick_accuracy: 49,
                    long_passing: 79,
                    short_passing: 82,
                    vision: 78,
                    physicality: 83,
                    aggression: 93,
                    stamina: 97,
                    jumping: 77,
                    strength: 72,
                    diving: 0,
                    handling: 0,
                    kicking: 0,
                    gk_positioning: 0,
                    reflexes: 0
                    },
                    rcm: {
                    id: 78,
                    resource_id: 192985,
                    rarity: 1,
                    common_name: "De Bruyne",
                    name: "Kevin De Bruyne",
                    first_name: "Kevin",
                    last_name: "Kevin De Bruyne",
                    rating: 91,
                    lw_meta_rating: 103.16,
                    lf_meta_rating: 98.24,
                    lm_meta_rating: 105.38,
                    lst_meta_rating: 106.75,
                    cst_meta_rating: 107.14,
                    rst_meta_rating: 110.75,
                    cf_meta_rating: 113.88,
                    rw_meta_rating: 100.16,
                    rf_meta_rating: 95.24,
                    rm_meta_rating: 102.38,
                    lcam_meta_rating: 99.04,
                    ccam_meta_rating: 108.73,
                    rcam_meta_rating: 99,
                    lcm_meta_rating: 87.9,
                    ccm_meta_rating: 89.71,
                    rcm_meta_rating: 87.92,
                    lcdm_meta_rating: 79.92,
                    ccdm_meta_rating: 79.92,
                    rcdm_meta_rating: 79.94,
                    lwb_meta_rating: 91.62,
                    lb_meta_rating: 78.45,
                    lcb_meta_rating: 76.94,
                    ccb_meta_rating: 76.94,
                    rcb_meta_rating: 76.98,
                    rwb_meta_rating: 91.66,
                    rb_meta_rating: 78.49,
                    gk_meta_rating: 27.82,
                    nation: 7,
                    league: 13,
                    club: 10,
                    position: "CM",
                    height: 181,
                    weight: 70,
                    attack_work_rate: "High",
                    defense_work_rate: "High",
                    foot: "Right",
                    weak_foot: 5,
                    skill_moves: 4,
                    shooting: 86,
                    positioning: 88,
                    finishing: 82,
                    shot_power: 91,
                    long_shots: 91,
                    volleys: 82,
                    penalties: 83,
                    defending: 64,
                    heading_accuracy: 55,
                    interceptions: 66,
                    sliding_tackle: 53,
                    standing_tackle: 65,
                    dribbling_face: 88,
                    agility: 79,
                    balance: 78,
                    ball_control: 91,
                    composure: 89,
                    dribbling: 88,
                    reactions: 91,
                    pace: 76,
                    acceleration: 76,
                    sprint_speed: 76,
                    passing: 93,
                    crossing: 94,
                    curve: 85,
                    free_kick_accuracy: 83,
                    long_passing: 93,
                    short_passing: 94,
                    vision: 94,
                    physicality: 78,
                    aggression: 76,
                    stamina: 89,
                    jumping: 63,
                    strength: 74,
                    diving: 0,
                    handling: 0,
                    kicking: 0,
                    gk_positioning: 0,
                    reflexes: 0
                    },
                    rm: {
                    id: 63,
                    resource_id: 209331,
                    rarity: 1,
                    common_name: "Salah",
                    name: "Mohamed Salah",
                    first_name: "Mohamed",
                    last_name: "Mohamed Salah",
                    rating: 89,
                    lw_meta_rating: 101.58,
                    lf_meta_rating: 97.2,
                    lm_meta_rating: 103.38,
                    lst_meta_rating: 107.94,
                    cst_meta_rating: 108.32,
                    rst_meta_rating: 107.9,
                    cf_meta_rating: 114.11,
                    rw_meta_rating: 108.58,
                    rf_meta_rating: 101.24,
                    rm_meta_rating: 111.38,
                    lcam_meta_rating: 101.03,
                    ccam_meta_rating: 103.62,
                    rcam_meta_rating: 101.07,
                    lcm_meta_rating: 78.89,
                    ccm_meta_rating: 80.62,
                    rcm_meta_rating: 78.87,
                    lcdm_meta_rating: 73.49,
                    ccdm_meta_rating: 73.47,
                    rcdm_meta_rating: 73.47,
                    lwb_meta_rating: 90.81,
                    lb_meta_rating: 75.64,
                    lcb_meta_rating: 73.55,
                    ccb_meta_rating: 73.51,
                    rcb_meta_rating: 73.51,
                    rwb_meta_rating: 90.77,
                    rb_meta_rating: 75.6,
                    gk_meta_rating: 27.54,
                    nation: 111,
                    league: 13,
                    club: 9,
                    position: "RW",
                    height: 175,
                    weight: 71,
                    attack_work_rate: "High",
                    defense_work_rate: "Med",
                    foot: "Left",
                    weak_foot: 3,
                    skill_moves: 4,
                    shooting: 87,
                    positioning: 91,
                    finishing: 91,
                    shot_power: 82,
                    long_shots: 84,
                    volleys: 81,
                    penalties: 86,
                    defending: 45,
                    heading_accuracy: 59,
                    interceptions: 55,
                    sliding_tackle: 41,
                    standing_tackle: 43,
                    dribbling_face: 90,
                    agility: 91,
                    balance: 91,
                    ball_control: 89,
                    composure: 90,
                    dribbling: 90,
                    reactions: 92,
                    pace: 90,
                    acceleration: 89,
                    sprint_speed: 91,
                    passing: 81,
                    crossing: 79,
                    curve: 83,
                    free_kick_accuracy: 69,
                    long_passing: 75,
                    short_passing: 84,
                    vision: 83,
                    physicality: 75,
                    aggression: 63,
                    stamina: 85,
                    jumping: 69,
                    strength: 75,
                    diving: 0,
                    handling: 0,
                    kicking: 0,
                    gk_positioning: 0,
                    reflexes: 0
                    },
                    lb: {
                    id: 64,
                    resource_id: 216267,
                    rarity: 1,
                    common_name: "Robertson",
                    name: "Andrew Robertson",
                    first_name: "Andrew",
                    last_name: "Andrew Robertson",
                    rating: 87,
                    lw_meta_rating: 88.6,
                    lf_meta_rating: 83.32,
                    lm_meta_rating: 91.52,
                    lst_meta_rating: 93.39,
                    cst_meta_rating: 93.69,
                    rst_meta_rating: 93.35,
                    cf_meta_rating: 98.72,
                    rw_meta_rating: 91.6,
                    rf_meta_rating: 83.36,
                    rm_meta_rating: 95.52,
                    lcam_meta_rating: 86.78,
                    ccam_meta_rating: 93.26,
                    rcam_meta_rating: 86.82,
                    lcm_meta_rating: 73.2,
                    ccm_meta_rating: 74.96,
                    rcm_meta_rating: 73.18,
                    lcdm_meta_rating: 77.5,
                    ccdm_meta_rating: 77.48,
                    rcdm_meta_rating: 77.48,
                    lwb_meta_rating: 95.06,
                    lb_meta_rating: 83.87,
                    lcb_meta_rating: 85.77,
                    ccb_meta_rating: 85.73,
                    rcb_meta_rating: 85.73,
                    rwb_meta_rating: 91.02,
                    rb_meta_rating: 79.83,
                    gk_meta_rating: 27.04,
                    nation: 42,
                    league: 13,
                    club: 9,
                    position: "LB",
                    height: 178,
                    weight: 64,
                    attack_work_rate: "High",
                    defense_work_rate: "High",
                    foot: "Left",
                    weak_foot: 2,
                    skill_moves: 3,
                    shooting: 61,
                    positioning: 77,
                    finishing: 55,
                    shot_power: 76,
                    long_shots: 65,
                    volleys: 32,
                    penalties: 55,
                    defending: 82,
                    heading_accuracy: 67,
                    interceptions: 83,
                    sliding_tackle: 81,
                    standing_tackle: 84,
                    dribbling_face: 81,
                    agility: 78,
                    balance: 74,
                    ball_control: 83,
                    composure: 83,
                    dribbling: 81,
                    reactions: 85,
                    pace: 84,
                    acceleration: 83,
                    sprint_speed: 85,
                    passing: 80,
                    crossing: 88,
                    curve: 82,
                    free_kick_accuracy: 50,
                    long_passing: 76,
                    short_passing: 82,
                    vision: 80,
                    physicality: 76,
                    aggression: 85,
                    stamina: 95,
                    jumping: 62,
                    strength: 65,
                    diving: 0,
                    handling: 0,
                    kicking: 0,
                    gk_positioning: 0,
                    reflexes: 0
                    },
                    lcb: {
                    id: 62,
                    resource_id: 203376,
                    rarity: 1,
                    common_name: "van Dijk",
                    name: "Virgil van Dijk",
                    first_name: "Virgil",
                    last_name: "Virgil van Dijk",
                    rating: 89,
                    lw_meta_rating: 81.67,
                    lf_meta_rating: 76.66,
                    lm_meta_rating: 85.63,
                    lst_meta_rating: 88.99,
                    cst_meta_rating: 90.58,
                    rst_meta_rating: 92.99,
                    cf_meta_rating: 93.76,
                    rw_meta_rating: 78.67,
                    rf_meta_rating: 73.66,
                    rm_meta_rating: 82.63,
                    lcam_meta_rating: 76.92,
                    ccam_meta_rating: 85.78,
                    rcam_meta_rating: 76.88,
                    lcm_meta_rating: 71.59,
                    ccm_meta_rating: 73.52,
                    rcm_meta_rating: 71.61,
                    lcdm_meta_rating: 82.73,
                    ccdm_meta_rating: 82.73,
                    rcdm_meta_rating: 82.75,
                    lwb_meta_rating: 84.34,
                    lb_meta_rating: 76.12,
                    lcb_meta_rating: 95.09,
                    ccb_meta_rating: 95.09,
                    rcb_meta_rating: 95.13,
                    rwb_meta_rating: 84.38,
                    rb_meta_rating: 76.16,
                    gk_meta_rating: 27.46,
                    nation: 34,
                    league: 13,
                    club: 9,
                    position: "CB",
                    height: 193,
                    weight: 92,
                    attack_work_rate: "Med",
                    defense_work_rate: "Med",
                    foot: "Right",
                    weak_foot: 3,
                    skill_moves: 2,
                    shooting: 60,
                    positioning: 47,
                    finishing: 52,
                    shot_power: 81,
                    long_shots: 64,
                    volleys: 45,
                    penalties: 62,
                    defending: 91,
                    heading_accuracy: 87,
                    interceptions: 90,
                    sliding_tackle: 86,
                    standing_tackle: 92,
                    dribbling_face: 72,
                    agility: 61,
                    balance: 53,
                    ball_control: 76,
                    composure: 90,
                    dribbling: 70,
                    reactions: 87,
                    pace: 78,
                    acceleration: 66,
                    sprint_speed: 88,
                    passing: 71,
                    crossing: 53,
                    curve: 60,
                    free_kick_accuracy: 70,
                    long_passing: 86,
                    short_passing: 79,
                    vision: 65,
                    physicality: 84,
                    aggression: 83,
                    stamina: 69,
                    jumping: 90,
                    strength: 92,
                    diving: 0,
                    handling: 0,
                    kicking: 0,
                    gk_positioning: 0,
                    reflexes: 0
                    },
                    rcb: {
                    id: 103,
                    resource_id: 201535,
                    rarity: 1,
                    common_name: "Varane",
                    name: "Raphaël Varane",
                    first_name: "Raphael",
                    last_name: "Raphaël Varane",
                    rating: 86,
                    lw_meta_rating: 76.36,
                    lf_meta_rating: 72.13,
                    lm_meta_rating: 79.64,
                    lst_meta_rating: 84.86,
                    cst_meta_rating: 86.19,
                    rst_meta_rating: 88.86,
                    cf_meta_rating: 89.28,
                    rw_meta_rating: 73.36,
                    rf_meta_rating: 69.13,
                    rm_meta_rating: 76.64,
                    lcam_meta_rating: 71.27,
                    ccam_meta_rating: 80.24,
                    rcam_meta_rating: 71.23,
                    lcm_meta_rating: 68.09,
                    ccm_meta_rating: 70,
                    rcm_meta_rating: 68.11,
                    lcdm_meta_rating: 77.73,
                    ccdm_meta_rating: 77.73,
                    rcdm_meta_rating: 77.75,
                    lwb_meta_rating: 83.01,
                    lb_meta_rating: 75.11,
                    lcb_meta_rating: 92.59,
                    ccb_meta_rating: 92.59,
                    rcb_meta_rating: 92.63,
                    rwb_meta_rating: 83.05,
                    rb_meta_rating: 75.15,
                    gk_meta_rating: 27.38,
                    nation: 18,
                    league: 13,
                    club: 11,
                    position: "CB",
                    height: 191,
                    weight: 81,
                    attack_work_rate: "Med",
                    defense_work_rate: "High",
                    foot: "Right",
                    weak_foot: 3,
                    skill_moves: 2,
                    shooting: 49,
                    positioning: 55,
                    finishing: 46,
                    shot_power: 52,
                    long_shots: 53,
                    volleys: 42,
                    penalties: 43,
                    defending: 87,
                    heading_accuracy: 86,
                    interceptions: 85,
                    sliding_tackle: 87,
                    standing_tackle: 88,
                    dribbling_face: 65,
                    agility: 62,
                    balance: 39,
                    ball_control: 78,
                    composure: 83,
                    dribbling: 55,
                    reactions: 84,
                    pace: 82,
                    acceleration: 79,
                    sprint_speed: 85,
                    passing: 64,
                    crossing: 42,
                    curve: 46,
                    free_kick_accuracy: 52,
                    long_passing: 76,
                    short_passing: 78,
                    vision: 59,
                    physicality: 82,
                    aggression: 80,
                    stamina: 76,
                    jumping: 81,
                    strength: 86,
                    diving: 0,
                    handling: 0,
                    kicking: 0,
                    gk_positioning: 0,
                    reflexes: 0
                    },
                    rb: {
                    id: 86,
                    resource_id: 210514,
                    rarity: 1,
                    common_name: "Cancelo",
                    name: "João Cancelo",
                    first_name: "João Pedro",
                    last_name: "João Cancelo",
                    rating: 86,
                    lw_meta_rating: 99.7,
                    lf_meta_rating: 94.51,
                    lm_meta_rating: 102.49,
                    lst_meta_rating: 101.42,
                    cst_meta_rating: 101.8,
                    rst_meta_rating: 105.42,
                    cf_meta_rating: 107.37,
                    rw_meta_rating: 96.7,
                    rf_meta_rating: 91.51,
                    rm_meta_rating: 99.49,
                    lcam_meta_rating: 95.2,
                    ccam_meta_rating: 100.86,
                    rcam_meta_rating: 95.16,
                    lcm_meta_rating: 77.51,
                    ccm_meta_rating: 79.33,
                    rcm_meta_rating: 77.53,
                    lcdm_meta_rating: 80.12,
                    ccdm_meta_rating: 80.12,
                    rcdm_meta_rating: 80.14,
                    lwb_meta_rating: 94.14,
                    lb_meta_rating: 82.34,
                    lcb_meta_rating: 85.67,
                    ccb_meta_rating: 85.67,
                    rcb_meta_rating: 85.71,
                    rwb_meta_rating: 98.18,
                    rb_meta_rating: 86.38,
                    gk_meta_rating: 27.64,
                    nation: 38,
                    league: 13,
                    club: 10,
                    position: "RB",
                    height: 182,
                    weight: 74,
                    attack_work_rate: "High",
                    defense_work_rate: "Med",
                    foot: "Right",
                    weak_foot: 4,
                    skill_moves: 4,
                    shooting: 71,
                    positioning: 80,
                    finishing: 68,
                    shot_power: 80,
                    long_shots: 75,
                    volleys: 62,
                    penalties: 46,
                    defending: 80,
                    heading_accuracy: 72,
                    interceptions: 80,
                    sliding_tackle: 80,
                    standing_tackle: 82,
                    dribbling_face: 84,
                    agility: 80,
                    balance: 78,
                    ball_control: 85,
                    composure: 85,
                    dribbling: 85,
                    reactions: 85,
                    pace: 85,
                    acceleration: 86,
                    sprint_speed: 84,
                    passing: 83,
                    crossing: 86,
                    curve: 84,
                    free_kick_accuracy: 69,
                    long_passing: 78,
                    short_passing: 85,
                    vision: 83,
                    physicality: 72,
                    aggression: 73,
                    stamina: 90,
                    jumping: 72,
                    strength: 62,
                    diving: 0,
                    handling: 0,
                    kicking: 0,
                    gk_positioning: 0,
                    reflexes: 0
                    },
                    gk: {
                    id: 79,
                    resource_id: 210257,
                    rarity: 1,
                    common_name: "Ederson",
                    name: "Ederson",
                    first_name: "Ederson",
                    last_name: "Ederson",
                    rating: 89,
                    lw_meta_rating: 57.47,
                    lf_meta_rating: 52.94,
                    lm_meta_rating: 61.13,
                    lst_meta_rating: 65.21,
                    cst_meta_rating: 66.66,
                    rst_meta_rating: 65.17,
                    cf_meta_rating: 67.79,
                    rw_meta_rating: 60.47,
                    rf_meta_rating: 52.98,
                    rm_meta_rating: 65.13,
                    lcam_meta_rating: 55.4,
                    ccam_meta_rating: 62.78,
                    rcam_meta_rating: 55.44,
                    lcm_meta_rating: 55.74,
                    ccm_meta_rating: 57.6,
                    rcm_meta_rating: 55.72,
                    lcdm_meta_rating: 50.88,
                    ccdm_meta_rating: 50.86,
                    rcdm_meta_rating: 50.86,
                    lwb_meta_rating: 56.09,
                    lb_meta_rating: 45.83,
                    lcb_meta_rating: 52.97,
                    ccb_meta_rating: 52.93,
                    rcb_meta_rating: 52.93,
                    rwb_meta_rating: 56.05,
                    rb_meta_rating: 45.79,
                    gk_meta_rating: 94.01,
                    nation: 54,
                    league: 13,
                    club: 10,
                    position: "GK",
                    height: 188,
                    weight: 86,
                    attack_work_rate: "Med",
                    defense_work_rate: "Med",
                    foot: "Left",
                    weak_foot: 3,
                    skill_moves: 1,
                    shooting: 31,
                    positioning: 20,
                    finishing: 14,
                    shot_power: 70,
                    long_shots: 18,
                    volleys: 18,
                    penalties: 51,
                    defending: 18,
                    heading_accuracy: 14,
                    interceptions: 27,
                    sliding_tackle: 8,
                    standing_tackle: 15,
                    dribbling_face: 51,
                    agility: 60,
                    balance: 48,
                    ball_control: 40,
                    composure: 70,
                    dribbling: 23,
                    reactions: 88,
                    pace: 63,
                    acceleration: 64,
                    sprint_speed: 63,
                    passing: 42,
                    crossing: 20,
                    curve: 15,
                    free_kick_accuracy: 20,
                    long_passing: 66,
                    short_passing: 61,
                    vision: 70,
                    physicality: 55,
                    aggression: 38,
                    stamina: 41,
                    jumping: 66,
                    strength: 78,
                    diving: 87,
                    handling: 82,
                    kicking: 93,
                    gk_positioning: 88,
                    reflexes: 88
                    }
                    })
            }

        }
    };
};

export default getState;